# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno
ARDUINO_DIR = /home/momofor/Downloads/arduino-1.8.13/
AVR_TOOLS_DIR = /usr
include /home/momofor/scripts/cpp/arduinoUno/test/Arduino.mk
AVRDUDE      = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
