title		Linux
linux	    /vmlinuz-linux
initrd      /booster-linux.img 
options		root=PARTUUID=be4ce13d-e750-bc47-abbc-f5aa27bf3934 quiet splash rw rootflags=relatime,compress=zstd:2,ssd,space_cache=v2,subvolid=5,subvol=/
