spacing = 2
padding = 0
hide_ascii = false
hide_bar_delimiters = true
prefer_small_ascii = false
separator = ">"
key_color = "Blue"
separator_color = "Cyan"
palette = "Light"

[box]
title = ""
visible = true

[box.inner_margin]
x = 1
y = 0

[custom_ascii]
color = "Blue"
path = "~/.config/macchina/archlinux.ascii"
