long_uptime = true
long_kernel = true
current_shell = true
show = ["Distribution","Kernel","Terminal","Packages","Shell","WindowManager","Uptime","Processor","ProcessorLoad","Memory","Host"]
theme = "noice"
