[package]
name = "sway-testing-with-ipc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swayipc = {version = "3.0.0-alpha.3"}
