source $HOME/.config/nvim/plug-config/coc.vim
source $HOME/.config/nvim/plug-config/sneak.vim
source $HOME/.config/nvim/general/general.vim
source $HOME/.config/nvim/plugged/plugins.vim
source $HOME/.config/nvim/hotkeys/hotkeys.vim
source $HOME/.config/nvim/theme-config/themeconfig.vim
source $HOME/.config/nvim/theme-config/airline.vim
source $HOME/.config/nvim/plug-config/fzf.vim
source $HOME/.config/nvim/plug-config/python-syntax.vim
"hello boys
