# script-opts=ytdl_hook-ytdl_path=yt-dlp 
# ytdl-format=bstvideo[height=720]+bestaudio/best
# ytdl-format="bestvideo[height=720]+bestaudio/best"
# ytdl-raw-options=cookies=/home/momofor/cookies.txt,extractor-args="youtube:player-client=default,-tv_simply"
# ytdl-raw-options=cookies=/home/momofor/cookies.txt
ytdl-raw-options=cookies=/home/momofor/cookies.txt
save-watch-history=yes
force-window=immediate
# cache-pause=yes

# Not too important on modern hardware. 'auto-copy-safe' is a safe option to use if one wants to enable it. Defaults to 'no'.
# hwdec=no

# Video driver to use. I recommend using the stable older 'gpu' (default) or the new experimental 'gpu-next'. Latter might still have various issues.
vo=gpu
###### Vulkan on Linux, Windows or macOS (recommended)
# gpu-api=vulkan
ao=pipewire

profile=fast

# [twitch]
# profile-cond=get("path", ""):find("^https://www.twitch.tv/") ~= nil
# profile-restore=copy-equal
# sub-font-size=30
# sub-align-x=right
# sub-align-y=top


# [deinterlace]
# profile-cond=p["video-frame-info/tff"]
# vf=bwdif

background-color='#1e1e2e'
osd-back-color='#11111b'
osd-border-color='#11111b'
osd-color='#cdd6f4'
osd-shadow-color='#1e1e2e'

# Stats script options
# Options are on separate lines for clarity
# Colors are in #BBGGRR format
script-opts-append=stats-border_color=251818
script-opts-append=stats-font_color=f4d6cd
script-opts-append=stats-plot_bg_border_color=febeb4
script-opts-append=stats-plot_bg_color=251818
script-opts-append=stats-plot_color=febeb4
