[package]
name = "wtf"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.14", features = ["full"]}
futures = "0.3.18"
reqwest = "0.11.6"
serde_json = "1.0.72"
