require("tele")
require("hotkeys")
require("options")
require("plugins")

require("compe-config")
require("mehu")
require("lsp-hotkeys")
require("ccGG")
--require("tsserveru")
require("lspsaga-config")
--require("navigator").setup()
require'colorizer'.setup()

require("variables")
require("groupsu")
--require("nvimtree-config")
require("treesitteru")
require("which-key").setup()
require'lsp_signature'.on_attach()
require("lineu")
