require("tele")
require("hotkeys")
require("options")
require("variables")
require("treesitteru")
require("plugins")
require("groupsu")

--require("compe-config")
--require("mehu")
--require("lsp-hotkeys")
--require("tsserveru")
--require("lspsaga-config")
require'colorizer'.setup()
